"""Tests for Code output generator."""

import sys
sys.path.insert(0, '/data/code/ai-collaboration-meeting/src')

import tempfile
from pathlib import Path
from outputs.code import CodeGenerator


def test_generate_python():
    """Test Python file generation."""
    with tempfile.TemporaryDirectory() as tmpdir:
        gen = CodeGenerator(Path(tmpdir))
        
        path = gen.generate_python("test", "def hello(): pass", "Test module")
        
        assert path.exists()
        content = path.read_text()
        assert '"""Generated by AI Collaboration Meeting Platform."""' in content
        assert "def hello(): pass" in content


def test_generate_javascript():
    """Test JavaScript file generation."""
    with tempfile.TemporaryDirectory() as tmpdir:
        gen = CodeGenerator(Path(tmpdir))
        
        path = gen.generate_javascript("test", "console.log('hi');")
        
        assert path.exists()
        content = path.read_text()
        assert "// Generated by AI" in content


if __name__ == "__main__":
    test_generate_python()
    test_generate_javascript()
    print("✅ Code generator tests passed!")