from __future__ import annotations

from pathlib import Path
from typing import Optional


class CodeGenerator:
    """Generate code files from meeting outputs."""

    def __init__(self, output_dir: Optional[Path] = None):
        self.output_dir = output_dir or Path("/data/code/ai-collaboration-meeting/outputs")
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_python(self, filename: str, code: str, description: str = "") -> Path:
        """Generate a Python file."""
        filepath = self.output_dir / f"{filename}.py"
        
        header = '"""Generated by AI Collaboration Meeting Platform."""\n\n'
        if description:
            header += f"# {description}\n\n"
        
        filepath.write_text(header + code, encoding="utf-8")
        return filepath

    def generate_javascript(self, filename: str, code: str, description: str = "") -> Path:
        """Generate a JavaScript file."""
        filepath = self.output_dir / f"{filename}.js"
        
        header = "// Generated by AI Collaboration Meeting Platform\n"
        if description:
            header += f"// {description}\n"
        
        filepath.write_text(header + code, encoding="utf-8")
        return filepath

    def generate_typescript(self, filename: str, code: str, description: str = "") -> Path:
        """Generate a TypeScript file."""
        filepath = self.output_dir / f"{filename}.ts"
        filepath.write_text(code, encoding="utf-8")
        return filepath


if __name__ == "__main__":
    gen = CodeGenerator()
    path = gen.generate_python("hello", "print('Hello World')", "Demo script")
    print(f"Generated: {path}")