"""Output Generator - generates meeting deliverables."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

OUTPUT_DIR = Path("/data/code/ai-collaboration-meeting/outputs")

STAGE_LABELS = {
    "requirement": "需求分析",
    "design": "设计方案",
    "coding": "编码阶段",
    "testing": "测试阶段",
    "documentation": "文档阶段",
}


class OutputGenerator:
    """Generates deliverables from meeting stages."""

    def __init__(self, meeting_id: str, output_dir: Optional[Path] = None):
        self.meeting_id = meeting_id
        self.output_dir = output_dir or OUTPUT_DIR / meeting_id
        # Only create if directory exists or we have permission
        try:
            self.output_dir.mkdir(parents=True, exist_ok=True)
        except (PermissionError, FileNotFoundError):
            pass

    def generate_markdown(self, title: str, content: str, stage_id: str = "output") -> Path:
        """Generate a Markdown document."""
        filename = f"{stage_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = self.output_dir / filename
        
        full_content = f"# {title}\n\n{content}\n\n---\n*Generated by AI Collaboration Meeting Platform*"
        filepath.write_text(full_content)
        
        return filepath

    def generate_code(self, filename: str, code: str, language: str = "python") -> Path:
        """Generate a code file."""
        if not filename.endswith(f".{language}"):
            filename = f"{filename}.{language}"
        
        filepath = self.output_dir / filename
        filepath.write_text(code)
        
        return filepath

    def list_outputs(self) -> List[Path]:
        """List all generated files."""
        return list(self.output_dir.glob("*"))


def format_meeting_summary(stage_logs: List[Dict[str, Any]]) -> str:
    """Format stage logs into a meeting summary Markdown."""
    lines = ["# 会议总结\n"]
    
    for stage in stage_logs:
        stage_type = stage.get("stage_type", "unknown")
        label = STAGE_LABELS.get(stage_type, stage_type.title())
        summary = stage.get("summary", "")
        decisions = stage.get("key_decisions", [])
        actions = stage.get("action_items", [])
        
        lines.append(f"## {label}\n")
        lines.append(f"{summary}\n")
        
        if decisions:
            lines.append("\n### 关键决定\n")
            for d in decisions:
                lines.append(f"- {d}\n")
        
        if actions:
            lines.append("\n### 待办事项\n")
            for a in actions:
                lines.append(f"- [ ] {a}\n")
    
    return "".join(lines)